"use client";

import { useEffect, useState } from "react";
import { DashboardLoading } from "@/components/DashboardShell";
import BuyingRatesPanel from "@/components/profitability/BuyingRatesPanel";
import FlightCostsPanel from "@/components/profitability/FlightCostsPanel";
import ProfitabilityOverviewPanel from "@/components/profitability/ProfitabilityOverviewPanel";
import ProfitabilitySelect from "@/components/profitability/ProfitabilitySelect";
import ShipmentMarginsTable from "@/components/profitability/ShipmentMarginsTable";
import { listBranches, type Branch } from "@/lib/branches";
import { getProfitabilityOverview, listProfitabilityShipments, listProfitabilityVendors, type LogisticsVendor, type ProfitabilityOverview, type ProfitabilityRow } from "@/lib/profitability";
import { FINANCE_AREA } from "@/lib/roles";
import { useAdminUser } from "@/lib/useAdminUser";

type Tab = "OVERVIEW" | "FLIGHTS" | "SHIPMENTS" | "RATES";
function indiaToday() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const value = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? ""; return `${value("year")}-${value("month")}-${value("day")}`; }

export default function ProfitabilityPage() {
  const { user, loading } = useAdminUser(FINANCE_AREA); const today = indiaToday();
  const [tab, setTab] = useState<Tab>("OVERVIEW"); const [branches, setBranches] = useState<Branch[]>([]); const [vendors, setVendors] = useState<LogisticsVendor[]>([]); const [overview, setOverview] = useState<ProfitabilityOverview | null>(null); const [rows, setRows] = useState<ProfitabilityRow[]>([]); const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 });
  const [branchId, setBranchId] = useState(""); const [service, setService] = useState(""); const [from, setFrom] = useState(`${today.slice(0, 7)}-01`); const [to, setTo] = useState(today); const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState(""); const [coverage, setCoverage] = useState(""); const [result, setResult] = useState(""); const [dataLoading, setDataLoading] = useState(true); const [error, setError] = useState("");

  async function reloadVendors() { const response = await listProfitabilityVendors(); setVendors(response.vendors); }
  useEffect(() => { if (!user) return; let active = true; Promise.all([listBranches("", "ACTIVE"), listProfitabilityVendors()]).then(([branchResult, vendorResult]) => { if (!active) return; setBranches(branchResult.branches); setVendors(vendorResult.vendors); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Profitability could not be loaded."); }).finally(() => { if (active) setDataLoading(false); }); return () => { active = false; }; }, [user]);
  useEffect(() => { if (!user) return; const handle = window.setTimeout(() => setSearch(searchInput.trim()), 300); return () => window.clearTimeout(handle); }, [searchInput, user]);
  useEffect(() => { if (!user || dataLoading) return; let active = true; Promise.all([getProfitabilityOverview({ branchId, service }), listProfitabilityShipments({ from, to, branchId, service, search, coverage, result, page: 1, limit: 25 })]).then(([overviewResult, shipmentResult]) => { if (!active) return; setOverview(overviewResult); setRows(shipmentResult.rows); setPagination({ page: shipmentResult.pagination.page, pages: shipmentResult.pagination.pages, total: shipmentResult.pagination.total }); setError(""); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Profitability could not be refreshed."); }); return () => { active = false; }; }, [branchId, coverage, dataLoading, from, result, search, service, to, user]);
  async function loadPage(page: number) { const response = await listProfitabilityShipments({ from, to, branchId, service, search, coverage, result, page, limit: 25 }); setRows(response.rows); setPagination({ page: response.pagination.page, pages: response.pagination.pages, total: response.pagination.total }); }
  if (loading || !user) return <DashboardLoading />;
  const showReportingFilters = tab === "OVERVIEW" || tab === "SHIPMENTS";

  return <div className="mx-auto max-w-[1600px] space-y-5">
    <header className="rounded-xl bg-white p-6 shadow-sm ring-1 ring-black/5"><p className="text-sm font-semibold text-[#0D1282]">Finance</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Profitability / Margin</h1></header>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1" aria-label="Profitability sections">{([{ id: "OVERVIEW", label: "Overview" }, { id: "FLIGHTS", label: "Flight costs" }, { id: "SHIPMENTS", label: "Shipment margins" }, { id: "RATES", label: "Buying rates" }] as Array<{ id: Tab; label: string }>).map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`h-10 whitespace-nowrap rounded-lg px-4 text-sm font-semibold transition ${tab === item.id ? "bg-[#0D1282] text-white" : "text-slate-600 hover:bg-slate-100 hover:text-slate-900"}`}>{item.label}</button>)}</nav>
    {tab !== "RATES" ? <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-end gap-3"><label className="min-w-52 text-sm font-semibold text-slate-700">Branch<ProfitabilitySelect value={branchId} onChange={(event) => setBranchId(event.target.value)} className="mt-2"><option value="">All accessible branches</option>{branches.map((branch) => <option key={branch._id} value={branch._id}>{branch.name} ({branch.code})</option>)}</ProfitabilitySelect></label>{showReportingFilters ? <label className="min-w-40 text-sm font-semibold text-slate-700">Service<ProfitabilitySelect value={service} onChange={(event) => setService(event.target.value)} className="mt-2"><option value="">All services</option><option value="COURIER">Courier</option><option value="CARGO">Cargo</option></ProfitabilitySelect></label> : null}{tab === "SHIPMENTS" ? <><label className="text-sm font-semibold text-slate-700">From<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} className="mt-2 block h-10 rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-[#0D1282]" /></label><label className="text-sm font-semibold text-slate-700">To<input type="date" value={to} min={from} max={today} onChange={(event) => setTo(event.target.value)} className="mt-2 block h-10 rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-[#0D1282]" /></label><label className="min-w-56 flex-1 text-sm font-semibold text-slate-700">Search<input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="AWB, customer or destination" className="mt-2 block h-10 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-[#0D1282]" /></label><label className="min-w-36 text-sm font-semibold text-slate-700">Coverage<ProfitabilitySelect value={coverage} onChange={(event) => setCoverage(event.target.value)} className="mt-2"><option value="">All</option><option value="ACTUAL">Actual</option><option value="ESTIMATED">Provisional</option><option value="PARTIAL">Partial</option><option value="MISSING">Missing</option></ProfitabilitySelect></label><label className="min-w-32 text-sm font-semibold text-slate-700">Result<ProfitabilitySelect value={result} onChange={(event) => setResult(event.target.value)} className="mt-2"><option value="">All</option><option value="PROFIT">Profit</option><option value="LOSS">Loss</option></ProfitabilitySelect></label></> : null}</div></section> : null}
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div> : null}
    {dataLoading ? <div className="rounded-xl border border-slate-200 bg-white py-16 text-center text-sm text-slate-500">Loading profitability…</div> : null}
    {!dataLoading && tab === "OVERVIEW" && overview ? <ProfitabilityOverviewPanel overview={overview} /> : null}
    {!dataLoading && tab === "FLIGHTS" ? <FlightCostsPanel branchId={branchId} /> : null}
    {!dataLoading && tab === "SHIPMENTS" ? <ShipmentMarginsTable rows={rows} page={pagination.page} pages={pagination.pages} total={pagination.total} onPage={(page) => void loadPage(page)} /> : null}
    {!dataLoading && tab === "RATES" ? <BuyingRatesPanel vendors={vendors} reloadVendors={reloadVendors} /> : null}
  </div>;
}
