"use client";

import { FormEvent, useEffect, useState } from "react";
import { FiArrowLeft, FiMapPin, FiRefreshCw, FiTruck } from "react-icons/fi";
import { toast } from "react-toastify";
import PickupProofGallery from "@/components/pickups/PickupProofGallery";
import { PickupNewBadge, PickupStatusBadge } from "@/components/pickups/PickupStatusBadge";
import type { Driver } from "@/lib/drivers";
import { assignInternalPickup, cancelInternalPickup, confirmInternalPickup, getInternalPickup, listAvailablePickupDrivers, listInternalPickups, pickupVehicleTypes, reviewInternalPickupOtpException, type PickupDetail, type PickupSummary } from "@/lib/pickups";

const address = (value: Record<string, string>) => [value.addressLine1, value.addressLine2, value.townOrCity, value.county, value.postcode].filter(Boolean).join(", ");
const format = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not confirmed";

export default function SupervisorPickupBoard() {
  const [pickups, setPickups] = useState<PickupSummary[]>([]);
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [selected, setSelected] = useState<PickupDetail | null>(null);
  const [windowStart, setWindowStart] = useState("");
  const [windowEnd, setWindowEnd] = useState("");
  const [driverId, setDriverId] = useState("");
  const [vehicle, setVehicle] = useState({ source: "DRIVER_OWNED", type: "", registrationNumber: "" });
  const [cancelReason, setCancelReason] = useState("");
  const [showCancel, setShowCancel] = useState(false);
  const [busy, setBusy] = useState(false);

  async function load() { const [pickupResult, driverResult] = await Promise.all([listInternalPickups(), listAvailablePickupDrivers()]); setPickups(pickupResult.pickups); setDrivers(driverResult.drivers); }
  useEffect(() => { let active = true; void Promise.all([listInternalPickups(), listAvailablePickupDrivers()]).then(([pickupResult, driverResult]) => { if (active) { setPickups(pickupResult.pickups); setDrivers(driverResult.drivers); } }).catch((caught) => toast.error(caught instanceof Error ? caught.message : "Unable to load dispatch.")); return () => { active = false; }; }, []);
  async function open(id: string) { setBusy(true); setShowCancel(false); try { setSelected((await getInternalPickup(id)).pickup); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to open pickup."); } finally { setBusy(false); } }
  async function confirm(event: FormEvent) { event.preventDefault(); if (!selected) return; setBusy(true); try { const result = await confirmInternalPickup(selected.id, { startAt: new Date(windowStart).toISOString(), endAt: new Date(windowEnd).toISOString(), timezone: "Asia/Kolkata" }); setSelected(result.pickup); toast.success("Pickup confirmed."); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to confirm pickup."); } finally { setBusy(false); } }
  async function assign(event: FormEvent) { event.preventDefault(); const attempt = selected?.attempts[0]; if (!selected || !attempt) return; setBusy(true); try { const result = await assignInternalPickup(selected.id, { attemptId: attempt._id, driverProfileId: driverId, vehicle }); setSelected(result.pickup); toast.success("Driver assigned."); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to assign driver."); } finally { setBusy(false); } }
  async function review(attemptId: string, approved: boolean) { if (!selected) return; setBusy(true); try { const result = await reviewInternalPickupOtpException(selected.id, { attemptId, approved }); setSelected(result.pickup); toast.success(result.message); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to review exception."); } finally { setBusy(false); } }
  async function cancel() { if (!selected || cancelReason.trim().length < 3) return; setBusy(true); try { const result = await cancelInternalPickup(selected.id, cancelReason); setSelected(result.pickup); setCancelReason(""); setShowCancel(false); toast.success(result.message); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to cancel pickup."); } finally { setBusy(false); } }

  if (selected) {
    const attempt = selected.attempts[0] ?? null;
    const canCancel = ["REQUESTED", "CONFIRMED", "ACTION_REQUIRED"].includes(selected.status) && (!attempt || ["SCHEDULED", "ASSIGNED"].includes(attempt.status));
    return <div className="space-y-4">
      <button onClick={() => setSelected(null)} className="inline-flex h-10 items-center gap-2 rounded-full bg-white px-4 text-sm font-semibold shadow-sm"><FiArrowLeft />All pickups</button>
      <section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Pickup request</p><h1 className="mt-1 text-xl font-bold">{selected.requestNumber}</h1></div><PickupStatusBadge status={selected.status} /></div><p className="mt-4 flex gap-2 text-sm text-slate-600"><FiMapPin className="mt-0.5 shrink-0" />{address(selected.pickupAddress)}</p><div className="mt-4 grid grid-cols-2 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-3"><strong className="text-xl">{selected.shipmentCount}</strong><p className="text-xs text-slate-500">Shipments</p></div><div className="rounded-2xl bg-slate-50 p-3"><strong className="text-xl">{selected.parcelCount}</strong><p className="text-xs text-slate-500">Parcels</p></div></div></section>
      {selected.status === "CANCELLED" ? <section className="rounded-3xl bg-slate-200 p-4"><strong>Cancelled by {selected.cancellationSource === "CLIENT" ? "Client" : "Admin"}</strong><p className="mt-1 text-xs text-slate-500">{format(selected.cancelledAt)}</p><p className="mt-2 text-sm">{selected.cancellationReason}</p></section> : null}
      {["REQUESTED", "PARTIALLY_COLLECTED"].includes(selected.status) ? <form onSubmit={confirm} className="rounded-3xl bg-white p-4 shadow-sm"><h2 className="font-bold">{selected.status === "PARTIALLY_COLLECTED" ? "Schedule remaining parcels" : "Confirm pickup window"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><input required type="datetime-local" value={windowStart} onChange={(event) => setWindowStart(event.target.value)} className="h-12 rounded-xl border border-slate-300 px-3" /><input required type="datetime-local" value={windowEnd} onChange={(event) => setWindowEnd(event.target.value)} className="h-12 rounded-xl border border-slate-300 px-3" /></div><button disabled={busy} className="mt-3 h-12 w-full rounded-xl bg-[#0D1282] font-semibold text-white">{selected.status === "PARTIALLY_COLLECTED" ? "Schedule retry" : "Confirm request"}</button></form> : null}
      {attempt && ["SCHEDULED", "ASSIGNED"].includes(attempt.status) ? <form onSubmit={assign} className="rounded-3xl bg-white p-4 shadow-sm"><h2 className="font-bold">Assign collection</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><select required value={driverId} onChange={(event) => setDriverId(event.target.value)} className="h-12 rounded-xl border border-slate-300 px-3"><option value="">Select active driver</option>{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.firstName} {driver.lastName} · {driver.engagementType.replace(/_/g, " ")}</option>)}</select><select value={vehicle.source} onChange={(event) => setVehicle((current) => ({ ...current, source: event.target.value }))} className="h-12 rounded-xl border border-slate-300 px-3"><option value="COMPANY_OWNED">Company vehicle</option><option value="DRIVER_OWNED">Driver vehicle</option><option value="HIRED">Hired vehicle</option></select><select required value={vehicle.type} onChange={(event) => setVehicle((current) => ({ ...current, type: event.target.value }))} className="h-12 rounded-xl border border-slate-300 px-3"><option value="">Select vehicle type</option>{pickupVehicleTypes.map((type) => <option key={type}>{type}</option>)}</select><input required placeholder="Registration number" value={vehicle.registrationNumber} onChange={(event) => setVehicle((current) => ({ ...current, registrationNumber: event.target.value }))} className="h-12 rounded-xl border border-slate-300 px-3 uppercase" /></div><button disabled={busy || !driverId} className="mt-3 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-400 font-bold text-slate-950"><FiTruck />Assign driver</button></form> : null}
      {selected.attempts.filter((item) => item.otpExceptionRequestedAt && !item.otpExceptionApprovedAt && !item.otpExceptionRejectedAt).map((item) => <section key={item._id} className="rounded-3xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-bold text-amber-950">OTP exception requested</h2><p className="mt-2 text-sm text-amber-900">{item.otpExceptionReason}</p><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={() => void review(item._id, true)} className="h-11 rounded-xl bg-emerald-600 text-sm font-semibold text-white">Approve</button><button disabled={busy} onClick={() => void review(item._id, false)} className="h-11 rounded-xl border border-red-300 bg-white text-sm font-semibold text-red-700">Reject</button></div></section>)}
      {attempt ? <section className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><strong>Attempt {attempt.sequence}</strong><PickupStatusBadge status={attempt.status} /></div><p className="mt-2 text-xs text-slate-500">{format(attempt.scheduledWindow.startAt)} - {format(attempt.scheduledWindow.endAt)}</p>{attempt.assignedDriverUserId ? <p className="mt-2 text-sm">Driver: {attempt.assignedDriverUserId.name || `${attempt.assignedDriverUserId.firstName ?? ""} ${attempt.assignedDriverUserId.lastName ?? ""}`}</p> : <p className="mt-2 text-sm text-slate-500">No driver assigned.</p>}</section> : null}
      <PickupProofGallery pickupId={selected.id} attempts={selected.attempts} audience="internal" />
      {canCancel ? <section className="rounded-3xl border border-red-200 bg-white p-4">{showCancel ? <><textarea value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} placeholder="Cancellation reason" className="min-h-20 w-full rounded-xl border border-red-300 p-3" /><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => setShowCancel(false)} className="h-11 rounded-xl border border-slate-300 font-semibold">Keep</button><button type="button" disabled={busy || cancelReason.trim().length < 3} onClick={() => void cancel()} className="h-11 rounded-xl bg-red-600 font-semibold text-white disabled:bg-slate-300">Cancel pickup</button></div></> : <button type="button" onClick={() => setShowCancel(true)} className="h-11 w-full rounded-xl border border-red-300 font-semibold text-red-700">Cancel pickup request</button>}</section> : null}
    </div>;
  }

  return <div className="space-y-4"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Pickup dispatch</h1><p className="mt-1 text-sm text-slate-500">Your assigned branches only.</p></div><button disabled={busy} onClick={() => void load()} className="flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-sm"><FiRefreshCw /></button></div><div className="grid gap-3 md:grid-cols-2">{pickups.map((pickup) => <button key={pickup.id} onClick={() => void open(pickup.id)} className="rounded-2xl bg-white p-4 text-left shadow-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{pickup.requestNumber}</strong><div className="flex gap-2">{pickup.status === "REQUESTED" ? <PickupNewBadge /> : null}<PickupStatusBadge status={pickup.status} /></div></div><p className="mt-2 text-sm text-slate-600">{pickup.pickupContact.name} · {pickup.parcelCount} parcels</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">{address(pickup.pickupAddress)}</p></button>)}</div>{!pickups.length ? <p className="rounded-3xl bg-white p-10 text-center text-sm text-slate-500">No pickup requests in your branches.</p> : null}</div>;
}
