"use client";

import { useCallback, useEffect, useState } from "react";
import { FiDownload, FiEye, FiRefreshCw,FiPlus } from "react-icons/fi";
import { toast } from "react-toastify";
import { formatDashboardDateTime } from "@/lib/dateFormat";
import DateFilterInput from "@/components/ui/DateFilterInput";
import Pagination from "@/components/ui/Pagination";
import {
  downloadShipmentManifest,
  listShipmentManifests,
  type ShipmentManifestAudience,
  type ShipmentManifestListItem,
} from "@/lib/shipmentManifests";
import Link from "next/dist/client/link";

export default function ManifestsListPage({
  audience,
}: {
  audience: ShipmentManifestAudience;
}) {
  const [manifests, setManifests] = useState<ShipmentManifestListItem[]>([]);
  const [pagination, setPagination] = useState({
    page: 1,
    limit: 15,
    total: 0,
    totalPages: 1,
  });
  const [page, setPage] = useState(1);
  const [date, setDate] = useState("");
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState("");
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await listShipmentManifests(audience, { page, date });
      setManifests(data.manifests);
      setPagination(data.pagination);
    } catch (caught) {
      setError(
        caught instanceof Error ? caught.message : "Unable to load manifests.",
      );
    } finally {
      setLoading(false);
    }
  }, [audience, date, page]);

  useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, [load]);

  // `view` opens the PDF in a new tab instead of saving it.
  async function handlePdf(manifest: ShipmentManifestListItem, view: boolean) {
    setBusyId(manifest.id);
    try {
      await downloadShipmentManifest(manifest, audience, view);
    } catch (caught) {
      toast.error(
        caught instanceof Error
          ? caught.message
          : "Manifest could not be opened.",
      );
    } finally {
      setBusyId("");
    }
  }

  return (
    <div className="mx-auto max-w-[1500px]">
      <div className="mb-5 flex flex-wrap items-start justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div>
          <h1 className="text-2xl font-semibold text-[#0D1282]">Manifests</h1>
          <p className="mt-1 text-sm text-slate-500">
            {audience === "client"
              ? "Manifests generated for your business accounts."
              : "Every shipment manifest generated in the portal."}
          </p>
        </div>
        {/* create manifest button */}
      <div className="flex items-center gap-2">
      <DateFilterInput
        value={date}
        onChange={(value) => {
          setDate(value);
          setPage(1);
        }}
      />
      <Link
  href={
    audience === "client"
      ? "/client/shipments"
      : "/dashboard/shipments"
  }
  className="inline-flex items-center justify-center rounded-4xl bg-[#0D1282] px-4 py-2 text-sm font-medium text-white hover:bg-[#0D1282]/90"
>
  <FiPlus className="mr-1" />
  Create Manifest
</Link>


        {/* <button
          type="button"
          onClick={() => void load()}
          title="Refresh"
          aria-label="Refresh manifests"
          className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-300 bg-white text-[#0D1282] hover:border-[#0D1282]"
        >
          <FiRefreshCw
            aria-hidden="true"
            className={`h-4 w-4 ${loading ? "animate-spin" : ""}`}
          />
        </button> */}
      </div>
      </div>

      {error ? (
        <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">
          {error}
        </div>
      ) : null}

      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full min-w-250 text-left text-sm">
            <thead className="bg-slate-200 text-xs uppercase text-slate-600 py-4">
              <tr>
                <th className="px-4 py-4">Manifest No</th>
                <th className="px-4 py-4">Route</th>
                <th className="px-4 py-4">Generated By</th>
                <th className="px-4 py-4 text-center">Shipments</th>
                <th className="px-4 py-4 text-center">Pcs</th>
                <th className="px-4 py-4 text-center">Weight</th>
                <th className="px-4 py-4">Created</th>
                <th className="px-4 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {manifests.map((manifest) => (
                <tr key={manifest.id} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-semibold text-[#0D1282]">
                    {manifest.manifestNumber}
                  </td>
                  <td className="px-4 py-3 text-slate-800">
                    {manifest.origin || manifest.destination
                      ? `${manifest.origin || "-"} → ${manifest.destination || "-"}`
                      : "Not specified"}
                  </td>
                  <td className="px-4 py-3 text-slate-800">
                    {manifest.generatedBy}
                    <p className="mt-0.5 text-xs capitalize text-slate-500">
                      {manifest.actorRole}
                    </p>
                  </td>
                  <td className="px-4 py-3 text-center tabular-nums text-slate-800">
                    {manifest.shipmentCount}
                  </td>
                  <td className="px-4 py-3 text-center tabular-nums text-slate-800">
                    {manifest.totalPieces}
                  </td>
                  <td className="px-4 py-3 text-center tabular-nums text-slate-800">
                    {manifest.totalWeightKg.toFixed(2)}
                  </td>
                  <td className="px-4 py-3 text-slate-600">
                    {formatDashboardDateTime(manifest.generatedAt)}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center justify-end gap-3">
                      <button
                        type="button"
                        onClick={() => void handlePdf(manifest, true)}
                        disabled={busyId === manifest.id}
                        className="inline-flex items-center gap-1 font-semibold text-[#0D1282] hover:text-blue-700 disabled:opacity-50"
                      >
                        <FiEye aria-hidden="true" className="h-4 w-4" />
                        Preview 
                      </button>
                      <button
                        type="button"
                        onClick={() => void handlePdf(manifest, false)}
                        disabled={busyId === manifest.id}
                        className="inline-flex items-center gap-1 font-semibold text-emerald-700 hover:text-emerald-800 disabled:opacity-50"
                      >
                        <FiDownload aria-hidden="true" className="h-4 w-4" />
                        {busyId === manifest.id
                          ? "Preparing..."
                          : "Download PDF"}
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {!loading && !manifests.length ? (
                <tr>
                  <td
                    colSpan={8}
                    className="px-4 py-14 text-center text-slate-500"
                  >
                    No manifests generated yet.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>
      </div>

      <Pagination
        page={pagination.page}
        totalPages={pagination.totalPages}
        total={pagination.total}
        onPageChange={setPage}
      />
    </div>
  );
}
